#!/usr/bin/env ruby
# Converts a CSV file into JSON, adding the gid key to all entries.

require "csv"
require "json"

unless ARGV.size >= 2
  puts "Usage: #{__FILE__} csvfile gameid"
  exit 1
end

input_path, gid = ARGV
output_path = input_path.sub(/\.csv$/, ".json")

file = CSV.read(input_path, headers: true)
list = file.map do |line|
  item = line.to_h
  item[:gid] = gid
  item
end

File.write(output_path, list.to_json)
