#!/usr/bin/env ruby

require 'csv'
require 'json'

file1 = CSV.read('1.csv', headers: true)
file2 = CSV.read('2.csv', headers: true)

list1 = file1.map{ |line| item = line.to_h ; item[:gid] = 1 ; item }
list2 = file2.map{ |line| item = line.to_h ; item[:gid] = 2 ; item }

File.write('cards.json', (list1 + list2).to_json)
